name: whillanscatalogpaper
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - cmap
  - ipykernel
  - matplotlib
  - pandas
  - pyproj
  - pytmd
  - rasterio
  - scipy
  - shapely
  - timescale
  - xarray
