# Rename file to main.yaml to perform code checks 
# Currently fails because pip install can't handle all dependencies at once

name: Code Checks
on: push
jobs:

  tests:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        runs-on: ['ubuntu-latest'] #,'macos-latest','windows-latest']
        allow_failure: [false]

    steps:
      # Actions are github's predefined task
      # View on https://github.com/marketplace/actions/checkout
      # @vX uses version X of the action
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install .[test]
    - run: coverage run -m pytest -m "not slow"
    - run: coverage report --show-missing
